version: '3'

services:
  jenkins:
    build:
      context: ./jenkins
    image: pgoultiaev/jenkins:latest
    networks:
      - ci
    ports:
      - "8081:8080"
  jenkins-exporter:
    build:
      context: ./jenkins_exporter
    image: pgoultiaev/jenkins_exporter
    ports:
      - "9118:9118"
    environment:
      - JENKINS_SERVER=http://jenkins:8080
      - JENKINS_PASS=admin
      - JENKINS_USER=admin
      - VIRTUAL_PORT=9118
      - DEBUG=1
    networks:
      - ci
    depends_on:
      - jenkins
  grafana:
    image: grafana/grafana:latest
    networks:
      - ci
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  prometheus:
    image: prom/prometheus:v2.1.0
    networks:
      - ci
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

networks:
  ci: