version: '3'

services:
  jenkins:
    build:
      context: ./jenkins
    image: pgoultiaev/jenkins:latest
    networks:
      - ci
    ports:
      - "8081:8080"
  jenkins-exporter:
    build:
      context: ./jenkins_exporter
    image: pgoultiaev/jenkins_exporter
    ports:
      - "9118:9118"
    environment:
      - JENKINS_SERVER=http://jenkins:8080
      - JENKINS_PASS=admin
      - JENKINS_USER=admin
      - VIRTUAL_PORT=9118
      - DEBUG=1
    networks:
      - ci
    depends_on:
      - jenkins
  telegraf:
    image: telegraf:1.4.0
    depends_on:
      - jenkins-exporter
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - ci
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  influxdb:
    image: influxdb:1.3.5
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - ci
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:latest
    networks:
      - ci
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  ci: