{
 "title": "Jenkins data",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "\n# Jenkins metrics" },
  {
   "title": "Mean job duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "jobname" ], "type": "tag" }
     ],
     "measurement": "jenkins_job_last_completed_build_duration_seconds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total jobs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "jobname" ], "type": "tag" }
     ],
     "measurement": "jenkins_job_last_successful_build",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "last 10 job success rate (Moving average)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "jobnumber" ], "type": "tag" }
     ],
     "measurement": "jenkins_job_last_build_result",
     "query": "SELECT moving_average(mean, 5) FROM (SELECT MEAN(\"gauge\") FROM \"jenkins_job_last_build_result\" GROUP BY \"jobnumber\")",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  }
 ]
}